apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
    name: http
    targetPort: 3306
    nodePort: 30002
  selector:
    app: mysql
