FROM kaggle/python:latest

RUN pip install jupyterlab -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com && \
    jupyter notebook --generate-config && \
    echo "import os" >> /root/.jupyter/jupyter_notebook_config.py && \
    echo "c.NotebookApp.token=os.getenv('APP_JUPYTER_TOKEN')" >> /root/.jupyter/jupyter_notebook_config.py

CMD ["jupyter-lab", "--ip=0.0.0.0", "--port=8888", "--allow-root"]

