apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rmqbroker
  labels:
    app: rmqbroker
spec:
  serviceName: rmqbroker
  replicas: 1
  selector:
    matchLabels:
      app: rmqbroker
  template:
    metadata:
      labels:
        app: rmqbroker
    spec:
      containers:
        - name: rmqbroker
          image: apacherocketmq/rocketmq:4.9.2
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1
              memory: 3Gi
            requests:
              cpu: 100m
              memory: 512Mi
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: JAVA_OPT_EXT
              value: "-server -Xms512m -Xmx1024m -Xmn256m  -XX:ParallelGCThreads=4"
          command: ["sh","mqbroker","-c","/etc/rocketmq/broker.conf","-n","rocketmq:9876","autoCreateTopicEnable=true"]
          ports:
            - containerPort: 10909
            - containerPort: 10911
            - containerPort: 10912
          volumeMounts:
            - name: vol-broker
              mountPath: /etc/rocketmq
      volumes:
        - name: vol-broker
          configMap:
              name: rocketmq-broker
