apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketmq-pv-logs
  labels:
    pvc: rocketmq-pv-logs
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/work/data/rocketmq/logs/"
