apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-logs-rmqbroker-0
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      pvc: rocketmq-pv-logs
