apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketmq-pv-store
  labels:
    pvc: rocketmq-pv-store
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/work/data/rocketmq/store/"
