apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rocketmq
  labels:
    app: rocketmq
spec:
  serviceName: rocketmq
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq
  template:
    metadata:
      labels:
        app: rocketmq
    spec:
      containers:
        - name: rocketmq
          image: apacherocketmq/rocketmq:4.9.2
          command: ["sh","mqnamesrv"]
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 3Gi
            requests:
              cpu: 100m
              memory: 768Mi
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: JAVA_OPT
              value: -Duser.home=/opt
            - name: JAVA_OPT_EXT
              value:  '-server -Xms1024m -Xmx1024m -Xmn256m'
          ports:
            - containerPort: 9876
